import type { PulseBarsProps, PulseDotsProps, PulseGridProps } from "./types"

/**
 * Curated, ready-to-use configurations. Each recipe is just props — spread
 * it onto the matching component:
 *
 *   const r = recipes.sonar
 *   <PulseGrid {...r.props} />
 */

export type Recipe =
  | { element: "grid"; title: string; blurb: string; props: PulseGridProps }
  | { element: "bars"; title: string; blurb: string; props: PulseBarsProps }
  | { element: "dots"; title: string; blurb: string; props: PulseDotsProps }

export const recipes = {
  sonar: {
    element: "grid",
    title: "Sonar",
    blurb: "Square rings expanding from the center, slow and glassy.",
    props: {
      rows: 5,
      cols: 5,
      cellSize: 7,
      gap: 4,
      radius: 2,
      pattern: "ripple",
      animate: "fade",
      easing: "drift",
      palette: "glacier",
      period: 1600,
      waves: 2,
    },
  },
  typing: {
    element: "dots",
    title: "Typing",
    blurb: "The classic three-dot bounce, tuned so the arc reads as a hop, not a wobble.",
    props: {
      count: 3,
      size: 7,
      gap: 4,
      animate: "bounce",
      pattern: "wave",
      envelope: { attack: 0.18, hold: 0, release: 0.3 },
      easing: "spring",
      period: 800,
    },
  },
  comet: {
    element: "dots",
    title: "Comet",
    blurb: "One bright head and a long gradient tail — phase coloring does the trailing.",
    props: {
      arrangement: "loop",
      count: 14,
      length: 5,
      thickness: 5,
      ringSize: 30,
      animate: "fade-scale",
      pattern: "wave",
      envelope: { attack: 0.02, hold: 0.05, release: 0.6 },
      colorBy: "phase",
      palette: "sherbet",
      period: 1200,
      dim: 0.06,
      restScale: 0.4,
    },
  },
  equalizer: {
    element: "bars",
    title: "Equalizer",
    blurb: "Upright bars breathing through a travelling wave — audio-meter energy.",
    props: {
      count: 7,
      thickness: 4,
      length: 24,
      animate: "stretch",
      pattern: "wave",
      envelope: "breathe",
      palette: "lagoon",
      period: 1000,
      waves: 1.5,
    },
  },
  galaxy: {
    element: "grid",
    title: "Galaxy",
    blurb: "A spiral phase field — the wave coils out from the center.",
    props: {
      rows: 7,
      cols: 7,
      cellSize: 4,
      gap: 3,
      pattern: "spiral",
      animate: "fade",
      palette: "ultraviolet",
      period: 2200,
      waves: 2,
      easing: "snap",
    },
  },
  static: {
    element: "grid",
    title: "Static",
    blurb: "Seeded shuffle + strobe envelope: tuned-between-stations TV noise.",
    props: {
      rows: 6,
      cols: 6,
      cellSize: 4,
      gap: 2,
      pattern: "sparkle",
      animate: "fade",
      envelope: "flash",
      palette: "mono",
      period: 700,
      waves: 3,
    },
  },
  glyph: {
    element: "dots",
    title: "Glyph",
    blurb: "An O drawn in dashes. Tune aspect and squareness until it matches your wordmark.",
    props: {
      arrangement: "loop",
      count: 12,
      length: 7,
      thickness: 3,
      ringSize: 30,
      aspect: 0.88,
      squareness: 2.6,
      animate: "fade",
      pattern: "wave",
      palette: "mono",
      period: 1100,
      dim: 0.2,
    },
  },
  monogram: {
    element: "bars",
    title: "Monogram",
    blurb:
      "A badge built from stripes — scanlines around a loop. Tune stroke and squareness to taste.",
    props: {
      arrangement: "loop",
      count: 8,
      ringSize: 32,
      aspect: 1.05,
      squareness: 2.2,
      stroke: 10,
      thickness: 2.5,
      radius: 1.25,
      animate: "fade",
      pattern: "wave",
      palette: "glacier",
      period: 1100,
      waves: 1.5,
    },
  },
  heartbeat: {
    element: "dots",
    title: "Heartbeat",
    blurb: "One dot, a double-beat envelope. Lub-dub.",
    props: {
      count: 1,
      size: 12,
      animate: "scale",
      pattern: "pulse",
      envelope: "heartbeat",
      palette: "ember",
      colorBy: "phase",
      period: 1200,
      restScale: 0.72,
    },
  },
  ticker: {
    element: "grid",
    title: "Ticker",
    blurb: "A wide, low strip of cells — the wave runs left to right like a marquee.",
    props: {
      rows: 3,
      cols: 14,
      cellSize: 4,
      gap: 2,
      radius: 1,
      pattern: "sweep-right",
      animate: "fade",
      palette: "aurora",
      period: 1800,
      waves: 2,
    },
  },
  stadium: {
    element: "dots",
    title: "Stadium",
    blurb: "A squircle track — the wave does laps around rounded corners.",
    props: {
      arrangement: "loop",
      count: 12,
      squareness: 4,
      aspect: 1.15,
      ringSize: 30,
      length: 6,
      thickness: 3,
      radius: 1.5,
      animate: "fade",
      pattern: "wave",
      palette: "ultraviolet",
      period: 1100,
      waves: 1.5,
    },
  },
  kelp: {
    element: "bars",
    title: "Kelp",
    blurb: "Bars pivoting at the root as the wave passes — wind through grass.",
    props: {
      count: 7,
      thickness: 3,
      length: 22,
      gap: 4,
      origin: "end",
      animate: "sway",
      amplitude: 16,
      envelope: "breathe",
      easing: "drift",
      pattern: "wave",
      waves: 1.5,
      palette: "moss",
      period: 1800,
    },
  },
  sunburst: {
    element: "dots",
    title: "Sunburst",
    blurb: "Radial ticks flaring around a ring — a clock face running hot.",
    props: {
      arrangement: "loop",
      align: "radial",
      count: 10,
      length: 8,
      thickness: 3,
      ringSize: 26,
      animate: "stretch",
      pattern: "wave",
      envelope: "flash",
      palette: "ember",
      period: 950,
      restScale: 0.45,
    },
  },
  drizzle: {
    element: "grid",
    title: "Drizzle",
    blurb: "Random cells stretching and flickering — rain streaks on a window.",
    props: {
      rows: 3,
      cols: 10,
      cellSize: 3.5,
      gap: 3,
      radius: 1.5,
      pattern: "sparkle",
      animate: "stretch",
      envelope: { attack: 0.3, hold: 0, release: 0.5 },
      palette: "lagoon",
      period: 1200,
      waves: 4,
      restScale: 0.25,
    },
  },
  metronome: {
    element: "dots",
    title: "Metronome",
    blurb: "Two dots trading places on a hard snap. Minimal, mechanical.",
    props: {
      count: 2,
      size: 8,
      gap: 6,
      pattern: "alternate",
      animate: "scale",
      easing: "snap",
      palette: "mono",
      period: 640,
      restScale: 0.35,
    },
  },
  breather: {
    element: "grid",
    title: "Breather",
    blurb: "The whole block inhales together — a calm idle state, not a busy one.",
    props: {
      rows: 3,
      cols: 3,
      cellSize: 7,
      gap: 3,
      radius: 2,
      pattern: "pulse",
      animate: "fade-scale",
      envelope: "breathe",
      easing: "drift",
      palette: "moss",
      period: 2000,
      restScale: 0.8,
      dim: 0.5,
    },
  },
  manuscript: {
    element: "bars",
    title: "Manuscript",
    blurb: "Flat lines growing from the left margin, like text being drafted.",
    props: {
      orientation: "horizontal",
      count: 5,
      thickness: 3,
      length: 34,
      gap: 5,
      origin: "start",
      animate: "stretch",
      pattern: "wave",
      envelope: "breathe",
      palette: "mono",
      period: 1500,
      restScale: 0.2,
    },
  },
  ascent: {
    element: "grid",
    title: "Ascent",
    blurb: "A wide chevron fold climbing the strip — directional, insistent.",
    props: {
      rows: 4,
      cols: 9,
      cellSize: 5,
      pattern: "chevron",
      animate: "fade",
      palette: "nocturne",
      period: 850,
      waves: 2,
    },
  },
  louver: {
    element: "bars",
    title: "Louver",
    blurb: "Flat slats flipping around their own axis — venetian blinds in a draft.",
    props: {
      orientation: "horizontal",
      count: 5,
      thickness: 4,
      length: 30,
      gap: 3,
      animate: "flip",
      pattern: "wave",
      palette: "glacier",
      period: 1400,
    },
  },
  orbit: {
    element: "dots",
    title: "Orbit",
    blurb: "A ring of dots the wave keeps lapping — spinner DNA, gradient body.",
    props: {
      arrangement: "loop",
      count: 8,
      length: 6,
      thickness: 6,
      ringSize: 26,
      animate: "fade-scale",
      pattern: "wave",
      period: 1000,
    },
  },
  beacon: {
    element: "dots",
    title: "Beacon",
    blurb: "Twelve small lights flashing fast around a tight ring — familiar shape, live color.",
    props: {
      arrangement: "loop",
      count: 12,
      length: 3.5,
      thickness: 3.5,
      ringSize: 22,
      animate: "fade",
      pattern: "wave",
      envelope: "flash",
      palette: "glacier",
      period: 700,
    },
  },
} satisfies Record<string, Recipe>

export type RecipeName = keyof typeof recipes
